### ISSUE TITLE
Everything got erased/corrupted for some reason.

### ISSUE THREAD

**Issue by Kiroto** [Kiroto/sumadora#2]
When I started up Visual Studio, It was all gone. Specifically THAT ONE project.

**Comment by Kiroto** [comment]
Oh, ok, it didn't erase. The program will still work. But the code and the design viewer aren't visible. I cannot access the code nor the visuals.

**Comment by iajrz** [comment]
You need to get better acquainted with Visual Studio :smile: Remember the "Solution Explorer" tab is what allows you to see and open the files. If for some reason it's nowhere to be found, look for it in the View menu.
